Webservinho: Logger Class Reference
Logger Class Reference
#include <utils/Logger.hpp>
Public Member Functions
~Logger ()
Closes the active log file on destruction.
void log (LogLevel level, const std::string &message)
Writes a log entry with timestamp, level, and message.
Static Public Member Functions
static Logger & instance ()
Returns the singleton instance of the Logger.
Detailed Description
Definition at line 22 of file Logger.hpp.
Constructor & Destructor Documentation
~Logger()
Logger::~Logger ()
Closes the active log file on destruction.
Definition at line 30 of file Logger.cpp.
Member Function Documentation
instance()
Logger & Logger::instance () static
Returns the singleton instance of the Logger.
Ensures that only one instance of Logger exists throughout execution.
Definition at line 37 of file Logger.cpp.
Referenced by ServerSocket::acceptConnections(), ClientConnection::adoptFD(), ResponseBuilder::build(), CgiHandler::buildEnvp(), Signals::checkCgiTimeouts(), ClientConnection::clearBuffer(), ClientConnection::ClientConnection(), ClientConnection::ClientConnection(), ClientConnection::completedRequest(), Dispatcher::dispatch(), WebServer::gracefulShutdown(), AutoIndexHandler::handle(), DeleteHandler::handle(), StaticPageHandler::handle(), UploadHandler::handle(), ResponseBuilder::handleCgiOutput(), RequestParse::handleRawRequest(), ServerSocket::listenConnections(), main(), WebServer::queueClientConnections(), WebServer::receiveRequest(), ClientConnection::recvData(), Signals::registerCgiProcess(), WebServer::removeClientConnection(), HttpRequest::reset(), HttpResponse::reset(), Router::resolve(), ResponseBuilder::responseWriter(), WebServer::runServer(), ClientConnection::sendData(), WebServer::sendResponse(), ServerSocket::ServerSocket(), ServerSocket::ServerSocket(), Signals::setupHandlers(), Signals::signalHandle(), CgiHandler::startAsync(), WebServer::startServer(), ServerSocket::startSocket(), Signals::unregisterCgiProcess(), WebServer::WebServer(), ClientConnection::~ClientConnection(), ServerSocket::~ServerSocket(), and WebServer::~WebServer().
log()
void Logger::log (LogLevel level, const std::string & message)
Writes a log entry with timestamp, level, and message.
Outputs to console depending on DEV mode:
DEV = 0: only INFO and higher.
DEV = 1: all levels. Always writes to the log file if open.
Definition at line 51 of file Logger.cpp.
References DEV, and INFO.
Referenced by ServerSocket::acceptConnections(), ClientConnection::adoptFD(), ResponseBuilder::build(), CgiHandler::buildEnvp(), Signals::checkCgiTimeouts(), ClientConnection::clearBuffer(), ClientConnection::ClientConnection(), ClientConnection::ClientConnection(), ClientConnection::completedRequest(), Dispatcher::dispatch(), WebServer::gracefulShutdown(), AutoIndexHandler::handle(), DeleteHandler::handle(), StaticPageHandler::handle(), UploadHandler::handle(), ResponseBuilder::handleCgiOutput(), RequestParse::handleRawRequest(), ServerSocket::listenConnections(), main(), WebServer::queueClientConnections(), WebServer::receiveRequest(), ClientConnection::recvData(), Signals::registerCgiProcess(), WebServer::removeClientConnection(), HttpRequest::reset(), HttpResponse::reset(), Router::resolve(), ResponseBuilder::responseWriter(), WebServer::runServer(), ClientConnection::sendData(), WebServer::sendResponse(), ServerSocket::ServerSocket(), ServerSocket::ServerSocket(), Signals::setupHandlers(), Signals::signalHandle(), CgiHandler::startAsync(), WebServer::startServer(), ServerSocket::startSocket(), Signals::unregisterCgiProcess(), WebServer::WebServer(), ClientConnection::~ClientConnection(), ServerSocket::~ServerSocket(), and WebServer::~WebServer().
The documentation for this class was generated from the following files:
includes/utils/Logger.hpp
srcs/utils/Logger.cpp