Webservinho: Router Class Reference
Router Class Reference
#include <dispatcher/Router.hpp>
Static Public Member Functions
static void resolve (HttpRequest &req, HttpResponse &res, ServerConfig const &config)
Main entry point for determining how an HTTP request should be handled.
Detailed Description
Definition at line 8 of file Router.hpp.
Member Function Documentation
resolve()
void Router::resolve (HttpRequest & req, HttpResponse & res, ServerConfig const & config) static
Main entry point for determining how an HTTP request should be handled.
The Router decides the appropriate route type based on request attributes, location configuration, and server rules. It checks for:
Parser errors or invalid URIs
Path traversal attempts
Redirects
CGI execution
File uploads
Autoindex directories
Static file serving
DELETE operations
On success, sets the correct RouteType and HTTP response status.
Definition at line 27 of file Router.cpp.
References RouteType::AutoIndex, RouteType::CGI, RouteType::Delete, RequestMethod::DELETE, RouteType::Error, ResponseStatus::Forbidden, RequestMethod::GET, LocationConfig::getCgiPath(), LocationConfig::getHasIndexFiles(), LocationConfig::getHasRoot(), LocationConfig::getIndex(), HttpRequest::getMethod(), HttpRequest::getParseError(), LocationConfig::getRoot(), ServerConfig::getRoot(), HttpRequest::getUri(), INFO, Logger::instance(), Logger::log(), ServerConfig::matchLocation(), ResponseStatus::MethodNotAllowed, ResponseStatus::NotFound, ResponseStatus::OK, RouteType::Redirect, HttpRequest::setRouteType(), HttpResponse::setStatusCode(), RouteType::StaticPage, RouteType::Upload, and WARNING.
Referenced by Dispatcher::dispatch().
The documentation for this class was generated from the following files:
includes/dispatcher/Router.hpp
srcs/dispatcher/Router.cpp