Webservinho: RequestParse Class Reference
RequestParse Class Reference
#include <request/RequestParse.hpp>
Static Public Member Functions
static void handleRawRequest (const std::string &rawRequest, HttpRequest &request, ServerConfig const &config)
Parses and processes raw HTTP request data incrementally.
Detailed Description
Definition at line 13 of file RequestParse.hpp.
Member Function Documentation
handleRawRequest()
void RequestParse::handleRawRequest (const std::string & chunk, HttpRequest & req, ServerConfig const & config) static
Parses and processes raw HTTP request data incrementally.
Handles the entire HTTP request flow: request line, headers, and body. Supports both Content-Length and chunked transfer encoding.
Definition at line 19 of file RequestParse.cpp.
References HttpRequest::addHeader(), HttpRequest::appendRaw(), ResponseStatus::BadRequest, RequestState::Body, HttpRequest::clearBuffer(), RequestState::Complete, DEBUG, HttpRequest::getBody(), HttpRequest::getBuffer(), ServerConfig::getClientMaxBodySize(), RequestMeta::getContentLength(), HttpRequest::getMeta(), HttpRequest::getParseError(), HttpRequest::getRaw(), HttpRequest::getState(), HttpRequest::hasHeader(), RequestState::Headers, Logger::instance(), RequestMeta::isChunked(), Logger::log(), ResponseStatus::OK, HttpRequest::removeHeader(), RequestState::RequestLine, RequestMeta::setChunked(), RequestMeta::setContentLength(), HttpRequest::setParseError(), HttpRequest::setRequestState(), and toString().
Referenced by ClientConnection::recvData().
The documentation for this class was generated from the following files:
includes/request/RequestParse.hpp
srcs/request/RequestParse.cpp